### ISSUE TITLE
Activity Prereq Courses

### ISSUE THREAD

**Issue by mvignal** [droundy/progressions-website#13]
If you look at the Valley, you will see that the prereq "The gradient is a local quantity" is attributed to Static Fields, when it is taught by the Hill activity in Vector Calc (the same class that the Valley is in) earlier in the progression. Not sure what the best outcome would be...

**Comment by droundy** [comment]
I think the challenge here is with concepts taught in multiple activities in multiple classes. I'm not sure how best to represent these things in prerequisites.  I think it's productive to categorize the prereq concepts it's just unclear how to do so when they are in multiple categories.
