### ISSUE TITLE
enable deleting representations

### ISSUE THREAD

**Issue by mvignal** [droundy/progressions-website#17]
Multiple times I have tried to make a C/R Pair and accidentally made a new representation. It would be really nice to be able to delete representations because it's starting to get unruly.

**Comment by droundy** [comment]
Hmmm.  I'll think about it.  For now, there is still the "gap" issue that I'd have to figure out.  I could possibly address that by giving deleted representations an empty name and recognize that as indicating "deleted".

There is also the question of whether I should search through the database to any reference to the to-be-deleted representation and delete those also.  Or disallow the deletion until all such links are removed?
